export const MONTHS = [
  'jan',
  'feb',
  'mar',
  'apr',
  'may',
  'jun',
  'jul',
  'aug',
  'sep',
  'oct',
  'nov',
  'dec',
];

export const WEATHER_ICONS = {
  '01d': 'clear-sky.svg',
  '01n': 'clear-sky-night.svg',
  '02d': 'few-clouds.svg',
  '02n': 'few-clouds-night.svg',
  '03d': 'scattered-clouds.svg',
  '03n': 'scattered-clouds.svg',
  '04d': 'overcast-clouds.svg',
  '04n': 'overcast-clouds.svg',
  '09d': 'heavy-rain.svg',
  '09n': 'heavy-rain.svg',
  '10d': 'light-rain.svg',
  '10n': 'light-rain-night.svg',
  '11d': 'thunderstorm-with-rain.svg',
  '11n': 'thunderstorm-with-rain-night.svg',
  '13d': 'snow.svg',
  '13n': 'snow.svg',
  '50d': 'fog.svg',
  '50n': 'fog.svg',
};

export const BACKGROUND_IMAGES = {
  '01d': 'clear-sky.jpg',
  '01n': 'clear-sky-night.jpg',
  '02d': 'few-clouds.jpg',
  '02n': 'few-clouds-night.jpg',
  '03d': 'scattered-clouds.jpg',
  '03n': 'scattered-clouds.jpg',
  '04d': 'overcast-clouds.jpg',
  '04n': 'overcast-clouds.jpg',
  '09d': 'heavy-rain.jpg',
  '09n': 'heavy-rain.jpg',
  '10d': 'light-rain.jpg',
  '10n': 'light-rain-night.jpg',
  '11d': 'thunderstorm-with-rain.jpg',
  '11n': 'thunderstorm-with-rain.jpg',
  '13d': 'snow.jpg',
  '13n': 'snow.jpg',
  '50d': 'scattered-clouds.jpg',
  '50n': 'scattered-clouds.jpg',
};
