export const messages = {
  en: {
    header: {
      home: 'Home',
      favorites: 'Favorites',
    },
    months: {
      jan: 'jan',
      feb: 'feb',
      mar: 'mar',
      apr: 'apr',
      may: 'may',
      jun: 'jun',
      jul: 'jul',
      aug: 'aug',
      sep: 'sep',
      oct: 'oct',
      nov: 'nov',
      dec: 'dec',
    },
    cityInputPlaceholder: 'Enter city name...',
    chartHeader: 'Temperature forecast',
    blockRemoveModalMsg: 'Remove it?',
    favoritesExceedModalMsg1: 'To add',
    favoritesExceedModalMsg2: 'first remove another city: maximum 5 favorites',
    favoritesEmptyHeader: 'Favorites list is empty!',
    favoritesEmptyMsg: 'Add something first.'
  },
  uk: {
    header: {
      home: 'Головна',
      favorites: 'Улюблене',
    },
    months: {
      jan: 'січ',
      feb: 'лют',
      mar: 'мар',
      apr: 'кві',
      may: 'тра',
      jun: 'чер',
      jul: 'лип',
      aug: 'сер',
      sep: 'вер',
      oct: 'жов',
      nov: 'лис',
      dec: 'гру',
    },
    cityInputPlaceholder: 'Напишіть назву міста...',
    chartHeader: 'Прогноз температури',
    blockRemoveModalMsg: 'Прибрати його?',
    favoritesExceedModalMsg1: 'Щоб додати',
    favoritesExceedModalMsg2: 'спочатку видаліть щось: не більше 5 улюблених міст.',
    favoritesEmptyHeader: 'Жодного улюбленого міста!',
    favoritesEmptyMsg: 'Додайте щось спочатку.'
  },
};